# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

import os
import urllib.request

# -- Project information -----------------------------------------------------

# General information about the project.
project = u'maliput'
copyright = u'2026 Woven by Toyota'
author = u'Woven By Toyota'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
  'sphinx_tabs.tabs',
  'sphinx_rtd_theme',
  'myst_parser',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# -- MyST-Parser configuration -----------------------------------------------

# Generate anchors for heading levels h1-h4 so in-page ToC links resolve.
myst_heading_anchors = 4

suppress_warnings = ['myst.xref_missing']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# Title of the html page.
html_title = "Maliput Documentation"

html_extra_path = ['media',
                   'from_doxygen']

# Icon of the window.
html_favicon = 'logo.png'

# Logo of the page. Logo will be put on top of the sidebar.
html_logo = 'logo.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
html_sidebars = { '**': ['globaltoc.html', 'relations.html', 'searchbox.html'] }

# If true, “Created using Sphinx” is shown in the HTML footer. Default is True.
html_show_sphinx = False
# -- Remote content fetching -------------------------------------------------

# Map of remote markdown files to fetch into the source tree before building.
# Keys are the local filename (relative to source dir), values are the raw URL.
REMOTE_MARKDOWN_FILES = {
    'maliput_geopackage_schema.md':
        'https://raw.githubusercontent.com/maliput/maliput_geopackage/main/schema/README.md',
}


def fetch_remote_content(app):
    """Download remote markdown files into the Sphinx source directory."""
    srcdir = app.srcdir
    for filename, url in REMOTE_MARKDOWN_FILES.items():
        dest = os.path.join(srcdir, filename)
        if not os.path.exists(dest):
            print(f'Fetching remote content: {url} -> {dest}')
            try:
                urllib.request.urlretrieve(url, dest)
            except Exception as e:
                print(f'Warning: Failed to fetch {url}: {e}')


def setup(app):
    app.connect('builder-inited', fetch_remote_content)
# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'maliput-doc'

# Html theme.
html_theme = 'sphinx_rtd_theme'
